"""empty message

Revision ID: a937f28b0bf7
Revises: 1045f330d461
Create Date: 2021-04-30 18:37:31.509738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a937f28b0bf7'
down_revision = '1045f330d461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'date_updated')
    # ### end Alembic commands ###
